apiVersion: v1
kind: Service
metadata:
  name: {{ include "patient-service.name" . }}
  labels:
    {{- include "patient-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "patient-service.labels" . | nindent 4 }}
